"""Export the robot model the phone app needs (kinematics + meshes) from MuJoCo.

    python export_phone_model.py        -> android/assets/robot_model.txt, robot_mesh.bin

Source of truth stays the rmd: the MJCF (../mujoco/mjcf/scene_servo.xml) is
generated from it, and this script only re-encodes the compiled model in a
form plain Java can read.  Nothing is typed in by hand except the robot's
joint travel limits (joint_limits_robot.json, measured on the robot, cited
there), which the rmd does not define.

robot_model.txt (whitespace separated, one record per line):
    body <id> <parent> <px py pz> <qw qx qy qz> <kind> <side> <k> <coef>
         kind: fixed | arm (joint k of arm side, angle = q_k) |
               passive (angle = coef * q_k of the same arm; wrist parallelogram)
         every joint rotates about the body's local +z at the body origin
    geom <body> <mesh> <px py pz> <qw qx qy qz> <r g b>
    arm  <side> <toolbody> <px py pz> <qw qx qy qz>
    home <side> <7 q>
    qmin <side> <7 q>     limits = robot travel  intersected with  model ctrlrange
    qmax <side> <7 q>
robot_mesh.bin (little endian): int nmesh, then per mesh
    int nvert, int nface, float[3*nvert] (mesh frame, m), int[3*nface]
"""

from __future__ import annotations

import json
import math
import struct
import sys
from pathlib import Path

import mujoco as mj
import numpy as np

HERE = Path(__file__).resolve().parent
MUJOCO_DIR = HERE.parent / "mujoco"
sys.path.insert(0, str(MUJOCO_DIR))
import loops  # noqa: E402

OUT = HERE / "android" / "assets"
SIDES = ("RA", "LA")


def passive_coef(m, side: str) -> dict[str, float]:
    """Fit passive = coef * q6 over the q6 range; check it is linear."""
    d = mj.MjData(m)
    q6 = m.joint(f"{side}_joint6").qposadr[0]
    out = {}
    xs = np.linspace(*m.actuator_ctrlrange[m.actuator(f"{side}_servo6").id], 15)
    for name in (f"{side}_joint6_1", f"{side}_joint6_2"):
        ys = []
        for x in xs:
            mj.mj_resetDataKeyframe(m, d, m.key("rmd_ic").id)
            d.qpos[q6] = x
            loops.close_loops(m, d)
            ys.append(d.qpos[m.joint(name).qposadr[0]])
        c = float(np.dot(xs, ys) / np.dot(xs, xs))
        res = float(np.max(np.abs(np.array(ys) - c * xs)))
        print(f"  {name} = {c:+.5f} * q6   (max residual {math.degrees(res):.3f} deg, visual only)")
        out[name] = c
    return out


def main() -> int:
    m = mj.MjModel.from_xml_path(str(MUJOCO_DIR / "mjcf" / "scene_servo.xml"))
    limits = json.loads((HERE / "joint_limits_robot.json").read_text(encoding="utf-8"))
    OUT.mkdir(parents=True, exist_ok=True)

    arm_joint = {}                                   # joint id -> (side, k)
    for side in SIDES:
        for k in range(7):
            arm_joint[m.joint(f"{side}_joint{k + 1}").id] = (side, k)
    passive = {}
    for side in SIDES:
        for name, c in passive_coef(m, side).items():
            passive[m.joint(name).id] = (side, 5, c)  # driven by q6 (index 5)

    lines = ["# generated by export_phone_model.py from mujoco/mjcf/scene_servo.xml - do not edit"]
    for b in range(1, m.nbody):                      # 0 = world (= base frame here)
        jn = m.body_jntnum[b]
        kind, side, k, coef = "fixed", "-", -1, 0.0
        if jn == 1:
            j = m.body_jntadr[b]
            assert np.allclose(m.jnt_axis[j], [0, 0, 1]) and np.allclose(m.jnt_pos[j], 0), m.joint(j).name
            if j in arm_joint:
                kind, (side, k) = "arm", arm_joint[j]
                coef = 1.0
            else:
                kind, (side, k, coef) = "passive", passive[j]
        else:
            assert jn == 0
        p, q = m.body_pos[b], m.body_quat[b]
        lines.append(f"body {b} {m.body_parentid[b]} {p[0]:.17g} {p[1]:.17g} {p[2]:.17g} "
                     f"{q[0]:.17g} {q[1]:.17g} {q[2]:.17g} {q[3]:.17g} {kind} {side} {k} {coef:.9g}")
    for g in range(m.ngeom):
        if m.geom_type[g] != mj.mjtGeom.mjGEOM_MESH:
            continue
        p, q, c = m.geom_pos[g], m.geom_quat[g], m.geom_rgba[g]
        lines.append(f"geom {m.geom_bodyid[g]} {m.geom_dataid[g]} {p[0]:.17g} {p[1]:.17g} {p[2]:.17g} "
                     f"{q[0]:.17g} {q[1]:.17g} {q[2]:.17g} {q[3]:.17g} {c[0]:.3f} {c[1]:.3f} {c[2]:.3f}")

    home_key = m.key("rmd_ic").id
    for side in SIDES:
        s = m.site(f"{side}_tool").id
        p, q = m.site_pos[s], m.site_quat[s]
        lines.append(f"arm {side} {m.site_bodyid[s]} {p[0]:.17g} {p[1]:.17g} {p[2]:.17g} "
                     f"{q[0]:.17g} {q[1]:.17g} {q[2]:.17g} {q[3]:.17g}")
        acts = [m.actuator(f"{side}_servo{i}").id for i in range(1, 8)]
        home = m.key_ctrl[home_key][acts]
        lo = np.maximum(m.actuator_ctrlrange[acts, 0], np.radians(limits[side]["min"]))
        hi = np.minimum(m.actuator_ctrlrange[acts, 1], np.radians(limits[side]["max"]))
        assert np.all(lo < home) and np.all(home < hi), f"{side} home outside limits"
        lines.append(f"home {side} " + " ".join(f"{v:.17g}" for v in home))
        lines.append(f"qmin {side} " + " ".join(f"{v:.17g}" for v in lo))
        lines.append(f"qmax {side} " + " ".join(f"{v:.17g}" for v in hi))
        print(f"  {side} limits [deg]: " + "  ".join(
            f"q{i + 1} {math.degrees(a):+.1f}..{math.degrees(b):+.1f}" for i, (a, b) in enumerate(zip(lo, hi))))
    (OUT / "robot_model.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")

    with open(OUT / "robot_mesh.bin", "wb") as f:
        f.write(struct.pack("<i", m.nmesh))
        for i in range(m.nmesh):
            va, vn = m.mesh_vertadr[i], m.mesh_vertnum[i]
            fa, fn = m.mesh_faceadr[i], m.mesh_facenum[i]
            f.write(struct.pack("<ii", vn, fn))
            f.write(np.asarray(m.mesh_vert[va:va + vn], "<f4").tobytes())
            f.write(np.asarray(m.mesh_face[fa:fa + fn], "<i4").tobytes())
    print(f"wrote {OUT / 'robot_model.txt'}  and  robot_mesh.bin "
          f"({(OUT / 'robot_mesh.bin').stat().st_size / 1e6:.1f} MB, {m.mesh_facenum.sum()} triangles)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
